services:
  db:
    build: db
    image: nodeapi-template_postgres-13-alpine-multi-user
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-node_db}
      POSTGRES_DBS: node_db,node_db_test
    volumes:
      - node_db:/var/lib/postgresql/data
    ports:
      - "${PG_PORT:-5444}:5432"
volumes:
  node_db:
